export enum ResponseCode {
  SUCCESS_OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  CLIENT_ERROR_BAD_REQUEST = 400,
  CLIENT_ERROR_UNAUTHORIZED = 401,
  CLIENT_ERROR_FORBIDDEN = 403,
  CLIENT_ERROR_NOT_FOUND = 404,
  CLIENT_ERROR_METHOD_NOT_ALLOWED = 405,
  CLIENT_ERROR_REQUEST_TIMEOUT = 408,
  CLIENT_ERROR_UNPROCESSABLE_ENTITY = 422,
  SERVER_ERROR_INTERNAL = 500,
  SERVER_ERROR_BAD_GATEWAY = 502,
  SERVER_ERROR_SERVICE_UNAVAILABLE = 503,
  SERVER_ERROR_GATEWAY_TIMEOUT = 504,
}

